/// @DnDAction : YoYo Games.Common.Execute_Code
/// @DnDVersion : 1
/// @DnDHash : 5CB4B8DC
/// @DnDArgument : "code" "/// @description Execute Code$(13_10)$(13_10)// Set the stats to equal the temp stats$(13_10)index					=  tempindex ;$(13_10)type					=  temptype				;$(13_10)levelreq				=  templevelreq			;$(13_10)mindamage				=  tempmindamage		;	$(13_10)maxdamage				=  tempmaxdamage		;	$(13_10)sockets					=  tempsockets			;	$(13_10)name					=  tempname				;$(13_10)description				=  tempdescription		;	$(13_10)rarity					=  temprarity			;	$(13_10)stackable				=  tempstackable		;	$(13_10)stackcount				=  tempstackcount		;	$(13_10)critical				=  tempcritical			;$(13_10)upgradelevel			=  tempupgradelevel		;$(13_10)sprite					=  tempsprite			;	$(13_10)spriteindex				=  tempspriteindex		;	$(13_10)healamount				=  temphealamount		;	$(13_10)defense					=  tempdefense			;	$(13_10)physresist				=  tempphysresist		;	$(13_10)fireresist				=  tempfireresist		;	$(13_10)lightningresist			=  templightningresist	;	$(13_10)iceresist				=  tempiceresist		;	$(13_10)lightresist				=  templightresist		;	$(13_10)shadowresist			=  tempshadowresist		;$(13_10)allelementresist		=  tempallelementresist	;$(13_10)subweapon				=  tempsubweapon		;	$(13_10)socket1					=  tempsocket1			;	$(13_10)socket2					=  tempsocket2			;	$(13_10)socket3					=  tempsocket3			;	$(13_10)abilities				=  tempabilities		;	$(13_10)ability1				=  tempability1			;$(13_10)ability2				=  tempability2			;$(13_10)ability3				=  tempability3			;$(13_10)statbonuses				=  tempstatbonuses		;	$(13_10)strbonus				=  tempstrbonus			;$(13_10)dexbonus				=  tempdexbonus			;$(13_10)intelbonus				=  tempintelbonus		;	$(13_10)vitbonus				=  tempvitbonus			;$(13_10)physbonus				=  tempphysbonus		;	$(13_10)firebonus				=  tempfirebonus		;	$(13_10)lightningbonus			=  templightningbonus	;	$(13_10)icebonus				=  tempicebonus			;$(13_10)lightbonus				=  templightbonus		;	$(13_10)shadowbonus				=  tempshadowbonus		;	$(13_10)allelementbonus			=  tempallelementbonus	;	$(13_10)set						=  tempset				;	$(13_10)setbonus1				=  tempsetbonus1		;	$(13_10)setbonus2				=  tempsetbonus2		;	$(13_10)setbonus3				=  tempsetbonus3		;	$(13_10)setdescription1			=  tempsetdescription1	;	$(13_10)setdescription2			=  tempsetdescription2	;	$(13_10)setdescription3			=  tempsetdescription3	;	$(13_10)statbonus1				=  tempstatbonus1		;	$(13_10)statbonus2				=  tempstatbonus2		;	$(13_10)statbonus3				=  tempstatbonus3		;	$(13_10)evasion					=  tempevasion			;	"
/// @description Execute Code

// Set the stats to equal the temp stats
index					=  tempindex ;
type					=  temptype				;
levelreq				=  templevelreq			;
mindamage				=  tempmindamage		;	
maxdamage				=  tempmaxdamage		;	
sockets					=  tempsockets			;	
name					=  tempname				;
description				=  tempdescription		;	
rarity					=  temprarity			;	
stackable				=  tempstackable		;	
stackcount				=  tempstackcount		;	
critical				=  tempcritical			;
upgradelevel			=  tempupgradelevel		;
sprite					=  tempsprite			;	
spriteindex				=  tempspriteindex		;	
healamount				=  temphealamount		;	
defense					=  tempdefense			;	
physresist				=  tempphysresist		;	
fireresist				=  tempfireresist		;	
lightningresist			=  templightningresist	;	
iceresist				=  tempiceresist		;	
lightresist				=  templightresist		;	
shadowresist			=  tempshadowresist		;
allelementresist		=  tempallelementresist	;
subweapon				=  tempsubweapon		;	
socket1					=  tempsocket1			;	
socket2					=  tempsocket2			;	
socket3					=  tempsocket3			;	
abilities				=  tempabilities		;	
ability1				=  tempability1			;
ability2				=  tempability2			;
ability3				=  tempability3			;
statbonuses				=  tempstatbonuses		;	
strbonus				=  tempstrbonus			;
dexbonus				=  tempdexbonus			;
intelbonus				=  tempintelbonus		;	
vitbonus				=  tempvitbonus			;
physbonus				=  tempphysbonus		;	
firebonus				=  tempfirebonus		;	
lightningbonus			=  templightningbonus	;	
icebonus				=  tempicebonus			;
lightbonus				=  templightbonus		;	
shadowbonus				=  tempshadowbonus		;	
allelementbonus			=  tempallelementbonus	;	
set						=  tempset				;	
setbonus1				=  tempsetbonus1		;	
setbonus2				=  tempsetbonus2		;	
setbonus3				=  tempsetbonus3		;	
setdescription1			=  tempsetdescription1	;	
setdescription2			=  tempsetdescription2	;	
setdescription3			=  tempsetdescription3	;	
statbonus1				=  tempstatbonus1		;	
statbonus2				=  tempstatbonus2		;	
statbonus3				=  tempstatbonus3		;	
evasion					=  tempevasion			;