/// @DnDAction : YoYo Games.Common.Execute_Code
/// @DnDVersion : 1
/// @DnDHash : 617A05EE
/// @DnDArgument : "code" "/// @description Execute Code itembar$(13_10)// Clear Mousestats -1;$(13_10)o_mouseitem.index				= -1;$(13_10)o_mouseitem.type				= -1;$(13_10)o_mouseitem.levelreq			= -1;$(13_10)o_mouseitem.mindamage			= -1;$(13_10)o_mouseitem.maxdamage			= -1;$(13_10)o_mouseitem.sockets				= -1;$(13_10)o_mouseitem.name				= -1;$(13_10)o_mouseitem.description			= -1;$(13_10)o_mouseitem.rarity				= -1;$(13_10)o_mouseitem.stackable			= -1;$(13_10)o_mouseitem.stackcount			= -1;$(13_10)o_mouseitem.critical			= -1;$(13_10)o_mouseitem.upgradelevel		= -1;$(13_10)o_mouseitem.sprite				= -1;$(13_10)o_mouseitem.spriteindex			= -1;$(13_10)o_mouseitem.healamount			= -1;$(13_10)o_mouseitem.defense				= -1;$(13_10)o_mouseitem.physresist			= -1;$(13_10)o_mouseitem.fireresist			= -1;$(13_10)o_mouseitem.lightningresist		= -1;$(13_10)o_mouseitem.iceresist			= -1;$(13_10)o_mouseitem.lightresist			= -1;$(13_10)o_mouseitem.shadowresist		= -1;$(13_10)o_mouseitem.allelementresist	= -1;$(13_10)o_mouseitem.subweapon			= -1;$(13_10)o_mouseitem.socket1				= -1;$(13_10)o_mouseitem.socket2				= -1;$(13_10)o_mouseitem.socket3				= -1;$(13_10)o_mouseitem.abilities			= -1;$(13_10)o_mouseitem.ability1			= -1;$(13_10)o_mouseitem.ability2			= -1;$(13_10)o_mouseitem.ability3			= -1;$(13_10)o_mouseitem.statbonuses			= -1;$(13_10)o_mouseitem.strbonus			= -1;$(13_10)o_mouseitem.dexbonus			= -1;$(13_10)o_mouseitem.intelbonus			= -1;$(13_10)o_mouseitem.vitbonus			= -1;$(13_10)o_mouseitem.physbonus			= -1;$(13_10)o_mouseitem.firebonus			= -1;$(13_10)o_mouseitem.lightningbonus		= -1;$(13_10)o_mouseitem.icebonus			= -1;$(13_10)o_mouseitem.lightbonus			= -1;$(13_10)o_mouseitem.shadowbonus			= -1;$(13_10)o_mouseitem.allelementbonus     = -1;$(13_10)o_mouseitem.set					= -1;$(13_10)o_mouseitem.setbonus1			= -1;$(13_10)o_mouseitem.setbonus2			= -1;$(13_10)o_mouseitem.setbonus3			= -1;$(13_10)o_mouseitem.setdescription1		= -1;$(13_10)o_mouseitem.setdescription2		= -1;$(13_10)o_mouseitem.setdescription3		= -1;$(13_10)o_mouseitem.statbonus1			= -1;$(13_10)o_mouseitem.statbonus2			= -1;$(13_10)o_mouseitem.statbonus3			= -1;$(13_10)o_mouseitem.evasion				= -1;"
/// @description Execute Code itembar
// Clear Mousestats -1;
o_mouseitem.index				= -1;
o_mouseitem.type				= -1;
o_mouseitem.levelreq			= -1;
o_mouseitem.mindamage			= -1;
o_mouseitem.maxdamage			= -1;
o_mouseitem.sockets				= -1;
o_mouseitem.name				= -1;
o_mouseitem.description			= -1;
o_mouseitem.rarity				= -1;
o_mouseitem.stackable			= -1;
o_mouseitem.stackcount			= -1;
o_mouseitem.critical			= -1;
o_mouseitem.upgradelevel		= -1;
o_mouseitem.sprite				= -1;
o_mouseitem.spriteindex			= -1;
o_mouseitem.healamount			= -1;
o_mouseitem.defense				= -1;
o_mouseitem.physresist			= -1;
o_mouseitem.fireresist			= -1;
o_mouseitem.lightningresist		= -1;
o_mouseitem.iceresist			= -1;
o_mouseitem.lightresist			= -1;
o_mouseitem.shadowresist		= -1;
o_mouseitem.allelementresist	= -1;
o_mouseitem.subweapon			= -1;
o_mouseitem.socket1				= -1;
o_mouseitem.socket2				= -1;
o_mouseitem.socket3				= -1;
o_mouseitem.abilities			= -1;
o_mouseitem.ability1			= -1;
o_mouseitem.ability2			= -1;
o_mouseitem.ability3			= -1;
o_mouseitem.statbonuses			= -1;
o_mouseitem.strbonus			= -1;
o_mouseitem.dexbonus			= -1;
o_mouseitem.intelbonus			= -1;
o_mouseitem.vitbonus			= -1;
o_mouseitem.physbonus			= -1;
o_mouseitem.firebonus			= -1;
o_mouseitem.lightningbonus		= -1;
o_mouseitem.icebonus			= -1;
o_mouseitem.lightbonus			= -1;
o_mouseitem.shadowbonus			= -1;
o_mouseitem.allelementbonus     = -1;
o_mouseitem.set					= -1;
o_mouseitem.setbonus1			= -1;
o_mouseitem.setbonus2			= -1;
o_mouseitem.setbonus3			= -1;
o_mouseitem.setdescription1		= -1;
o_mouseitem.setdescription2		= -1;
o_mouseitem.setdescription3		= -1;
o_mouseitem.statbonus1			= -1;
o_mouseitem.statbonus2			= -1;
o_mouseitem.statbonus3			= -1;
o_mouseitem.evasion				= -1;