/// @DnDAction : YoYo Games.Common.Execute_Code
/// @DnDVersion : 1
/// @DnDHash : 114FAB4A
/// @DnDArgument : "code" "/// @description Execute Code$(13_10)o_mouseitem.tempindex			=global.inventory[slot]; // Beware$(13_10)o_mouseitem.temptype			=global.inventory[slot+1,0];$(13_10)o_mouseitem.templevelreq		=global.inventory[slot+1,1];$(13_10)o_mouseitem.tempmindamage		=global.inventory[slot+1,2];$(13_10)o_mouseitem.tempmaxdamage		=global.inventory[slot+1,3];$(13_10)o_mouseitem.tempsockets			=global.inventory[slot+1,4];$(13_10)o_mouseitem.tempname			=global.inventory[slot+1,5];$(13_10)o_mouseitem.tempdescription		=global.inventory[slot+1,6];$(13_10)o_mouseitem.temprarity			=global.inventory[slot+1,7];$(13_10)o_mouseitem.tempstackable		=global.inventory[slot+1,8];$(13_10)o_mouseitem.tempstackcount		=global.inventory[slot+1,9];$(13_10)o_mouseitem.tempcritical		=global.inventory[slot+1,10];$(13_10)o_mouseitem.tempupgradelevel	=global.inventory[slot+1,11];$(13_10)o_mouseitem.tempsprite			=global.inventory[slot+1,12];$(13_10)o_mouseitem.tempspriteindex		=global.inventory[slot+1,13];$(13_10)o_mouseitem.temphealamount		=global.inventory[slot+1,14];$(13_10)o_mouseitem.tempdefense			=global.inventory[slot+1,15];$(13_10)o_mouseitem.tempphysresist		=global.inventory[slot+1,16];$(13_10)o_mouseitem.tempfireresist		=global.inventory[slot+1,17];$(13_10)o_mouseitem.templightningresist	=global.inventory[slot+1,18];$(13_10)o_mouseitem.tempiceresist		=global.inventory[slot+1,19];$(13_10)o_mouseitem.templightresist		=global.inventory[slot+1,20];$(13_10)o_mouseitem.tempshadowresist	=global.inventory[slot+1,21];$(13_10)o_mouseitem.tempallelementresist=global.inventory[slot+1,22];$(13_10)o_mouseitem.tempsubweapon		=global.inventory[slot+1,23];$(13_10)o_mouseitem.tempsocket1			=global.inventory[slot+1,24];$(13_10)o_mouseitem.tempsocket2			=global.inventory[slot+1,25];$(13_10)o_mouseitem.tempsocket3			=global.inventory[slot+1,26];$(13_10)o_mouseitem.tempabilities		=global.inventory[slot+1,27];$(13_10)o_mouseitem.tempability1		=global.inventory[slot+1,28];$(13_10)o_mouseitem.tempability2		=global.inventory[slot+1,29];$(13_10)o_mouseitem.tempability3		=global.inventory[slot+1,30];$(13_10)o_mouseitem.tempstatbonuses		=global.inventory[slot+1,31];$(13_10)o_mouseitem.tempstrbonus		=global.inventory[slot+1,32];$(13_10)o_mouseitem.tempdexbonus		=global.inventory[slot+1,33];$(13_10)o_mouseitem.tempintelbonus		=global.inventory[slot+1,34];$(13_10)o_mouseitem.tempvitbonus		=global.inventory[slot+1,35];$(13_10)o_mouseitem.tempphysbonus		=global.inventory[slot+1,36];$(13_10)o_mouseitem.tempfirebonus		=global.inventory[slot+1,37];$(13_10)o_mouseitem.templightningbonus	=global.inventory[slot+1,38];$(13_10)o_mouseitem.tempicebonus		=global.inventory[slot+1,39];$(13_10)o_mouseitem.templightbonus		=global.inventory[slot+1,40];$(13_10)o_mouseitem.tempshadowbonus		=global.inventory[slot+1,41];$(13_10)o_mouseitem.tempallelementbonus	=global.inventory[slot+1,42];$(13_10)o_mouseitem.tempset				=global.inventory[slot+1,43];$(13_10)o_mouseitem.tempsetbonus1		=global.inventory[slot+1,44];$(13_10)o_mouseitem.tempsetbonus2		=global.inventory[slot+1,45];$(13_10)o_mouseitem.tempsetbonus3		=global.inventory[slot+1,46];$(13_10)o_mouseitem.tempsetdescription1	=global.inventory[slot+1,47];$(13_10)o_mouseitem.tempsetdescription2	=global.inventory[slot+1,48];$(13_10)o_mouseitem.tempsetdescription3	=global.inventory[slot+1,49];$(13_10)o_mouseitem.tempstatbonus1		=global.inventory[slot+1,50];$(13_10)o_mouseitem.tempstatbonus2		=global.inventory[slot+1,51];$(13_10)o_mouseitem.tempstatbonus3		=global.inventory[slot+1,52];$(13_10)o_mouseitem.evasion				=global.inventory[slot+1,53];"
/// @description Execute Code
o_mouseitem.tempindex			=global.inventory[slot]; // Beware
o_mouseitem.temptype			=global.inventory[slot+1,0];
o_mouseitem.templevelreq		=global.inventory[slot+1,1];
o_mouseitem.tempmindamage		=global.inventory[slot+1,2];
o_mouseitem.tempmaxdamage		=global.inventory[slot+1,3];
o_mouseitem.tempsockets			=global.inventory[slot+1,4];
o_mouseitem.tempname			=global.inventory[slot+1,5];
o_mouseitem.tempdescription		=global.inventory[slot+1,6];
o_mouseitem.temprarity			=global.inventory[slot+1,7];
o_mouseitem.tempstackable		=global.inventory[slot+1,8];
o_mouseitem.tempstackcount		=global.inventory[slot+1,9];
o_mouseitem.tempcritical		=global.inventory[slot+1,10];
o_mouseitem.tempupgradelevel	=global.inventory[slot+1,11];
o_mouseitem.tempsprite			=global.inventory[slot+1,12];
o_mouseitem.tempspriteindex		=global.inventory[slot+1,13];
o_mouseitem.temphealamount		=global.inventory[slot+1,14];
o_mouseitem.tempdefense			=global.inventory[slot+1,15];
o_mouseitem.tempphysresist		=global.inventory[slot+1,16];
o_mouseitem.tempfireresist		=global.inventory[slot+1,17];
o_mouseitem.templightningresist	=global.inventory[slot+1,18];
o_mouseitem.tempiceresist		=global.inventory[slot+1,19];
o_mouseitem.templightresist		=global.inventory[slot+1,20];
o_mouseitem.tempshadowresist	=global.inventory[slot+1,21];
o_mouseitem.tempallelementresist=global.inventory[slot+1,22];
o_mouseitem.tempsubweapon		=global.inventory[slot+1,23];
o_mouseitem.tempsocket1			=global.inventory[slot+1,24];
o_mouseitem.tempsocket2			=global.inventory[slot+1,25];
o_mouseitem.tempsocket3			=global.inventory[slot+1,26];
o_mouseitem.tempabilities		=global.inventory[slot+1,27];
o_mouseitem.tempability1		=global.inventory[slot+1,28];
o_mouseitem.tempability2		=global.inventory[slot+1,29];
o_mouseitem.tempability3		=global.inventory[slot+1,30];
o_mouseitem.tempstatbonuses		=global.inventory[slot+1,31];
o_mouseitem.tempstrbonus		=global.inventory[slot+1,32];
o_mouseitem.tempdexbonus		=global.inventory[slot+1,33];
o_mouseitem.tempintelbonus		=global.inventory[slot+1,34];
o_mouseitem.tempvitbonus		=global.inventory[slot+1,35];
o_mouseitem.tempphysbonus		=global.inventory[slot+1,36];
o_mouseitem.tempfirebonus		=global.inventory[slot+1,37];
o_mouseitem.templightningbonus	=global.inventory[slot+1,38];
o_mouseitem.tempicebonus		=global.inventory[slot+1,39];
o_mouseitem.templightbonus		=global.inventory[slot+1,40];
o_mouseitem.tempshadowbonus		=global.inventory[slot+1,41];
o_mouseitem.tempallelementbonus	=global.inventory[slot+1,42];
o_mouseitem.tempset				=global.inventory[slot+1,43];
o_mouseitem.tempsetbonus1		=global.inventory[slot+1,44];
o_mouseitem.tempsetbonus2		=global.inventory[slot+1,45];
o_mouseitem.tempsetbonus3		=global.inventory[slot+1,46];
o_mouseitem.tempsetdescription1	=global.inventory[slot+1,47];
o_mouseitem.tempsetdescription2	=global.inventory[slot+1,48];
o_mouseitem.tempsetdescription3	=global.inventory[slot+1,49];
o_mouseitem.tempstatbonus1		=global.inventory[slot+1,50];
o_mouseitem.tempstatbonus2		=global.inventory[slot+1,51];
o_mouseitem.tempstatbonus3		=global.inventory[slot+1,52];
o_mouseitem.evasion				=global.inventory[slot+1,53];