/// @DnDAction : YoYo Games.Common.Execute_Code
/// @DnDVersion : 1
/// @DnDHash : 07B184CE
/// @DnDArgument : "code" "/// @description Execute Code$(13_10)// Mousestats to Array$(13_10)			//global.inventory[slot]		= o_mouseitem.index;$(13_10)			global.inventory[slot+1,0]  = o_mouseitem.type				 ;$(13_10)			global.inventory[slot+1,1] 	= o_mouseitem.levelreq			 ;$(13_10)			global.inventory[slot+1,2] 	= o_mouseitem.mindamage			 ;$(13_10)			global.inventory[slot+1,3] 	= o_mouseitem.maxdamage			 ;$(13_10)			global.inventory[slot+1,4] 	= o_mouseitem.sockets			 ;$(13_10)			global.inventory[slot+1,5] 	= o_mouseitem.name				 ;$(13_10)			global.inventory[slot+1,6] 	= o_mouseitem.description		 ;$(13_10)			global.inventory[slot+1,7] 	= o_mouseitem.rarity			 ;$(13_10)			global.inventory[slot+1,8] 	= o_mouseitem.stackable			 ;$(13_10)			global.inventory[slot+1,9] 	= o_mouseitem.stackcount		 ;$(13_10)			global.inventory[slot+1,10]	= o_mouseitem.critical				 ;$(13_10)			global.inventory[slot+1,11]	= o_mouseitem.upgradelevel		 ;$(13_10)			global.inventory[slot+1,12]	= o_mouseitem.sprite			 ;$(13_10)			global.inventory[slot+1,13]	= o_mouseitem.spriteindex		 ;$(13_10)			global.inventory[slot+1,14]	= o_mouseitem.healamount		 ;$(13_10)			global.inventory[slot+1,15]	= o_mouseitem.defense			 ;$(13_10)			global.inventory[slot+1,16]	= o_mouseitem.physresist		 ;$(13_10)			global.inventory[slot+1,17]	= o_mouseitem.fireresist		 ;$(13_10)			global.inventory[slot+1,18]	= o_mouseitem.lightningresist	 ;$(13_10)			global.inventory[slot+1,19]	= o_mouseitem.iceresist			 ;$(13_10)			global.inventory[slot+1,20]	= o_mouseitem.lightresist		 ;$(13_10)			global.inventory[slot+1,21]	= o_mouseitem.shadowresist		 ;$(13_10)			global.inventory[slot+1,22]	= o_mouseitem.allelementresist	 ;$(13_10)			global.inventory[slot+1,23]	= o_mouseitem.subweapon			 ;$(13_10)			global.inventory[slot+1,24]	= o_mouseitem.socket1			 ;$(13_10)			global.inventory[slot+1,25]	= o_mouseitem.socket2			 ;$(13_10)			global.inventory[slot+1,26]	= o_mouseitem.socket3			 ;$(13_10)			global.inventory[slot+1,27]	= o_mouseitem.abilities			 ;$(13_10)			global.inventory[slot+1,28]	= o_mouseitem.ability1			 ;$(13_10)			global.inventory[slot+1,29]	= o_mouseitem.ability2			 ;$(13_10)			global.inventory[slot+1,30]	= o_mouseitem.ability3			 ;$(13_10)			global.inventory[slot+1,31]	= o_mouseitem.statbonuses		 ;$(13_10)			global.inventory[slot+1,32]	= o_mouseitem.strbonus			 ;$(13_10)			global.inventory[slot+1,33]	= o_mouseitem.dexbonus			 ;$(13_10)			global.inventory[slot+1,34]	= o_mouseitem.intelbonus		 ;$(13_10)			global.inventory[slot+1,35]	= o_mouseitem.vitbonus			 ;$(13_10)			global.inventory[slot+1,36]	= o_mouseitem.physbonus			 ;$(13_10)			global.inventory[slot+1,37]	= o_mouseitem.firebonus			 ;$(13_10)			global.inventory[slot+1,38]	= o_mouseitem.lightningbonus	 ;$(13_10)			global.inventory[slot+1,39]	= o_mouseitem.icebonus			 ;$(13_10)			global.inventory[slot+1,40]	= o_mouseitem.lightbonus		 ;$(13_10)			global.inventory[slot+1,41]	= o_mouseitem.shadowbonus		 ;$(13_10)			global.inventory[slot+1,42]	= o_mouseitem.allelementbonus	 ;$(13_10)			global.inventory[slot+1,43]	= o_mouseitem.set				 ;$(13_10)			global.inventory[slot+1,44]	= o_mouseitem.setbonus1			 ;$(13_10)			global.inventory[slot+1,45]	= o_mouseitem.setbonus2			 ;$(13_10)			global.inventory[slot+1,46]	= o_mouseitem.setbonus3			 ;$(13_10)			global.inventory[slot+1,47]	= o_mouseitem.setdescription1	 ;$(13_10)			global.inventory[slot+1,48]	= o_mouseitem.setdescription2	 ;$(13_10)			global.inventory[slot+1,49]	= o_mouseitem.setdescription3	 ;$(13_10)			global.inventory[slot+1,50]	= o_mouseitem.statbonus1		 ;$(13_10)			global.inventory[slot+1,51]	= o_mouseitem.statbonus2		 ;$(13_10)			global.inventory[slot+1,52]	= o_mouseitem.statbonus3		 ;$(13_10)			global.inventory[slot+1,53]	= o_mouseitem.evasion			 ;"
/// @description Execute Code
// Mousestats to Array
			//global.inventory[slot]		= o_mouseitem.index;
			global.inventory[slot+1,0]  = o_mouseitem.type				 ;
			global.inventory[slot+1,1] 	= o_mouseitem.levelreq			 ;
			global.inventory[slot+1,2] 	= o_mouseitem.mindamage			 ;
			global.inventory[slot+1,3] 	= o_mouseitem.maxdamage			 ;
			global.inventory[slot+1,4] 	= o_mouseitem.sockets			 ;
			global.inventory[slot+1,5] 	= o_mouseitem.name				 ;
			global.inventory[slot+1,6] 	= o_mouseitem.description		 ;
			global.inventory[slot+1,7] 	= o_mouseitem.rarity			 ;
			global.inventory[slot+1,8] 	= o_mouseitem.stackable			 ;
			global.inventory[slot+1,9] 	= o_mouseitem.stackcount		 ;
			global.inventory[slot+1,10]	= o_mouseitem.critical				 ;
			global.inventory[slot+1,11]	= o_mouseitem.upgradelevel		 ;
			global.inventory[slot+1,12]	= o_mouseitem.sprite			 ;
			global.inventory[slot+1,13]	= o_mouseitem.spriteindex		 ;
			global.inventory[slot+1,14]	= o_mouseitem.healamount		 ;
			global.inventory[slot+1,15]	= o_mouseitem.defense			 ;
			global.inventory[slot+1,16]	= o_mouseitem.physresist		 ;
			global.inventory[slot+1,17]	= o_mouseitem.fireresist		 ;
			global.inventory[slot+1,18]	= o_mouseitem.lightningresist	 ;
			global.inventory[slot+1,19]	= o_mouseitem.iceresist			 ;
			global.inventory[slot+1,20]	= o_mouseitem.lightresist		 ;
			global.inventory[slot+1,21]	= o_mouseitem.shadowresist		 ;
			global.inventory[slot+1,22]	= o_mouseitem.allelementresist	 ;
			global.inventory[slot+1,23]	= o_mouseitem.subweapon			 ;
			global.inventory[slot+1,24]	= o_mouseitem.socket1			 ;
			global.inventory[slot+1,25]	= o_mouseitem.socket2			 ;
			global.inventory[slot+1,26]	= o_mouseitem.socket3			 ;
			global.inventory[slot+1,27]	= o_mouseitem.abilities			 ;
			global.inventory[slot+1,28]	= o_mouseitem.ability1			 ;
			global.inventory[slot+1,29]	= o_mouseitem.ability2			 ;
			global.inventory[slot+1,30]	= o_mouseitem.ability3			 ;
			global.inventory[slot+1,31]	= o_mouseitem.statbonuses		 ;
			global.inventory[slot+1,32]	= o_mouseitem.strbonus			 ;
			global.inventory[slot+1,33]	= o_mouseitem.dexbonus			 ;
			global.inventory[slot+1,34]	= o_mouseitem.intelbonus		 ;
			global.inventory[slot+1,35]	= o_mouseitem.vitbonus			 ;
			global.inventory[slot+1,36]	= o_mouseitem.physbonus			 ;
			global.inventory[slot+1,37]	= o_mouseitem.firebonus			 ;
			global.inventory[slot+1,38]	= o_mouseitem.lightningbonus	 ;
			global.inventory[slot+1,39]	= o_mouseitem.icebonus			 ;
			global.inventory[slot+1,40]	= o_mouseitem.lightbonus		 ;
			global.inventory[slot+1,41]	= o_mouseitem.shadowbonus		 ;
			global.inventory[slot+1,42]	= o_mouseitem.allelementbonus	 ;
			global.inventory[slot+1,43]	= o_mouseitem.set				 ;
			global.inventory[slot+1,44]	= o_mouseitem.setbonus1			 ;
			global.inventory[slot+1,45]	= o_mouseitem.setbonus2			 ;
			global.inventory[slot+1,46]	= o_mouseitem.setbonus3			 ;
			global.inventory[slot+1,47]	= o_mouseitem.setdescription1	 ;
			global.inventory[slot+1,48]	= o_mouseitem.setdescription2	 ;
			global.inventory[slot+1,49]	= o_mouseitem.setdescription3	 ;
			global.inventory[slot+1,50]	= o_mouseitem.statbonus1		 ;
			global.inventory[slot+1,51]	= o_mouseitem.statbonus2		 ;
			global.inventory[slot+1,52]	= o_mouseitem.statbonus3		 ;
			global.inventory[slot+1,53]	= o_mouseitem.evasion			 ;